### ISSUE TITLE
Can't compile it?

### ISSUE THREAD

**Issue by ghost** [casavi/potoo#1]
The instructions in readme are not clear. There is no folder build to cd to run cmake.
No experience compiling c++ from source.
Thanks in advance

**Comment by d0b1010r** [comment]
@MHeimbuc can probably help you out better, but I think the readme misses the step that you need to create (`mkdir build`) the build folder first, and only then `cd` into it. Hope that helps.

**Comment by d0b1010r** [comment]
Closing b/c of inactivity.
